// Code generated by mockery v2.45.0. DO NOT EDIT.

package vault

import (
	context "context"

	api "github.com/hashicorp/vault/api"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *MockClient) Client() *api.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 *api.Client
	if rf, ok := ret.Get(0).(func() *api.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Client)
		}
	}

	return r0
}

// GetKvSecretV2 provides a mock function with given fields: ctx, mount, name
func (_m *MockClient) GetKvSecretV2(ctx context.Context, mount string, name string) (*api.KVSecret, error) {
	ret := _m.Called(ctx, mount, name)

	if len(ret) == 0 {
		panic("no return value specified for GetKvSecretV2")
	}

	var r0 *api.KVSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*api.KVSecret, error)); ok {
		return rf(ctx, mount, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *api.KVSecret); ok {
		r0 = rf(ctx, mount, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.KVSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, mount, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSecret provides a mock function with given fields: ctx, path
func (_m *MockClient) GetSecret(ctx context.Context, path string) (*Secrets, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *Secrets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Secrets, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Secrets); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Secrets)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetKvSecretV2 provides a mock function with given fields: ctx, mount, name, data
func (_m *MockClient) SetKvSecretV2(ctx context.Context, mount string, name string, data map[string]interface{}) error {
	ret := _m.Called(ctx, mount, name, data)

	if len(ret) == 0 {
		panic("no return value specified for SetKvSecretV2")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, mount, name, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransitDecrypt provides a mock function with given fields: ctx, data
func (_m *MockClient) TransitDecrypt(ctx context.Context, data string) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for TransitDecrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransitEncrypt provides a mock function with given fields: ctx, data
func (_m *MockClient) TransitEncrypt(ctx context.Context, data string) (*Secrets, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for TransitEncrypt")
	}

	var r0 *Secrets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Secrets, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Secrets); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Secrets)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
